#!/bin/bash

# Go to current script location.
cd "$(dirname ${BASH_SOURCE})"

git fetch origin master
git merge origin master

# Rsync it to homedir."
rsync \
  --exclude .git/ \
  --exclude *.ignore \
  --exclude source \
  --exclude .Xresources \
  --exclude .config/ \
  -avh --no-perms . ~

# If vim-plug exist, don't download it again
if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim +PlugUpdate! +qa
